version: '3'
services:
  sqldef:
    build: './docker/sqldef'
    volumes:
      - './docker/sqldef/volume:/volume'
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      - db
  db:
    image: 'mysql:8.1.0'
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - '3306:3306'
volumes:
  db-store:
