[versions]
kotlin = "1.7.21"
springPlugin = "1.7.21"
springBoot = "2.7.5"
springDependencyManagement = "1.0.15.RELEASE"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }

[libraries]
spring-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-starter-test = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
jackson-module-kotlin  = "com.fasterxml.jackson.module:jackson-module-kotlin:2.14.0"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
