name: Docker Image Build & Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for image'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for code differences
        id: diff
        run: echo ::set-output name=diff::$(git diff --name-only  | grep 'backend\/.*\/src\/.*\.kt$' || echo "true")

      #- name: Semantic Versioning
      #  id: semver
      #  run: |
      #    # Perform semantic versioning calculations and output the result
      #    echo ::set-output name=tag::$(YOUR_SEMANTIC_VERSIONING_LOGIC_HERE)

      #- name: Build Docker image with semantic version tag
      #  if: ${{ github.event_name == 'push' && steps.diff-check.outputs.diff == 'true' }}
      #  run: docker build -t api:${{ steps.semver.outputs.tag }} .

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: "{context}/backend/api/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
