name: Docker Image Build & Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for image'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Check for code differences
        id: diff
        run: echo ::set-output name=diff::$(git diff --name-only  | grep 'backend\/.*\/src\/.*\.kt$' || echo "true")

      - name: docker setup
        id: dockerSetup
        shell: sh
        run: |
          docker compose up -d db --wait

      - name: setup
        shell: sh
        run: make setup

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/api/Dockerfile
          push: true
          no-cache: true
          tags: ghcr.io/${{ github.actor }}/gradle-multi-project-api:${{ github.event.inputs.tag }}
