name: Front test

on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      front: ${{ steps.changes.outputs.front }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check diff
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            front:
              - front/app/public/**
              - front/app/src/**
              - front/app/**
  test:
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.front == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - name: docker setup
        id: dockerSetup
        shell: sh
        run: |
          docker compose up -d db --wait
      - name: prepare
        shell: sh
        run: |
          make setup
      - name: test
        id: test
        run: make test-frontend
