name: Kotlin test

on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check diff
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            api:
              - 'gradle/libs.versions.toml'
              - 'build.gradle.kts'
              - 'backend/api/src/main/**'
              - 'backend/api/build.gradle.kts'
              - 'backend/domains/src/main/**'
              - 'backend/domains/build.gradle.kts'
              - 'backend/infrastructure/src/main/**'
              - 'backend/infrastructure/build.gradle.kts'
              - 'docker/sqldef/volume/schema.sql'
  test:
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.api == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: docker setup
        id: dockerSetup
        shell: sh
        run: |
          docker compose up -d db --wait
      - name: prepare
        shell: sh
        run: |
          make setup-backend
      - name: Setup and execute Gradle 'test' task
        id: lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - name: Check detekt file exists
        id: checkDetektFile
        run: |
          if [ -f "build/reports/detekt/detekt.sarif" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
      - name: Unit test
        id: unitTest
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ failure() && steps.lint.conclusion == 'failure' && steps.checkDetektFile.outputs.exists == 'true' }}
        with:
          sarif_file: build/reports/detekt/detekt.sarif
