name: Kotlin test

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: docker setup
        id: dockerSetup
        shell: sh
        run: |
          docker compose up -d db --wait
      - name: prepare
        shell: sh
        run: |
          make db-migrate-local
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup and execute Gradle 'test' task
        id: lint
        run: |
          ./gradlew detekt
      - name: Check detekt file exists
        id: checkDetektFile
        run: |
          if [ -f "build/reports/detekt/detekt.sarif" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
      - name: Unit test
        id: unitTest
        run: |
          ./gradlew test
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ failure() && steps.lint.conclusion == 'failure' && steps.checkDetektFile.outputs.exists == 'true' }}
        with:
          sarif_file: build/reports/detekt/detekt.sarif
