name: Kotlin test

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup and execute Gradle 'test' task
        id: lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ failure() && steps.lint.conclusion == 'failure' && hasFiles('build/reports/detekt/detekt.sarif') }}
        with:
          sarif_file: build/reports/detekt/detekt.sarif
