name: migrate database

on:
  workflow_dispatch:

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Migration
        run: make db-migrate-remote
