name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check diff
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            api:
              - 'gradle/libs.versions.toml'
              - 'build.gradle.kts'
              - 'backend/api/src/main/**'
              - 'backend/api/build.gradle.kts'
              - 'backend/domains/src/main/**'
              - 'backend/domains/build.gradle.kts'
              - 'backend/infrastructure/src/main/**'
              - 'backend/infrastructure/build.gradle.kts'
              - 'docker/sqldef/volume/schema.sql'

      - name: Release API
        if: steps.changes.outputs.api == 'true'
        uses: ./.github/workflows/docker-image-push.yml
        with:
          tag: ${{ github.sha }}
